language: python
python:
  - "3.3"

install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"

before_script:
  - "cd app"
  - "cd tests"

script:
  - coverage run -m unittest 
after_success:
  - coveralls 