language: python
python:
  - "3.3"

install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"

before_script:
  - "cd app"
  
script:
  - coverage run --omit=core.py,app.py,templating.py  --source=. -m unittest discover -s tests/
after_success:
  - coveralls 